// Curated project cards.
// Each row is rendered as a hard table entry — no cards, no gradients.
// lang = short code (PY, TS, RS, GO, SOL, JS, C++) shown in the LANG column.
// langColor = solid color of the language swatch.
window.PROJECTS = [
  {
    repo: "face-lock",
    title: "Face-Lock",
    desc: "Face-recognition CLI that auto-locks your laptop the moment you walk away. Computer vision + presence detection done right.",
    tag: "computer vision",
    lang: "PY",
    langColor: "#FFD43B",
    size: "wide",
    topics: ["python", "opencv", "cli"],
  },
  {
    repo: "face-lock-site",
    title: "Face-Lock.site",
    desc: "Marketing site for the Face-Lock CLI.",
    tag: "frontend",
    lang: "TS",
    langColor: "#3178C6",
    size: "narrow",
    topics: ["typescript", "marketing"],
  },
  {
    repo: "shoppingshield",
    title: "ShoppingShield",
    desc: "Anti-scam platform that protects users from fraudulent e-commerce sites. Real-time risk scoring and browser tooling.",
    tag: "consumer · safety",
    lang: "TS",
    langColor: "#3178C6",
    size: "narrow",
    topics: ["typescript", "security"],
  },
  {
    repo: "btc-perp-hft-framework",
    title: "BTC-Perp HFT",
    desc: "High-frequency trading framework for BTC perpetual futures on Coinbase International. Built for low-latency research and execution.",
    tag: "hft · infra",
    lang: "PY",
    langColor: "#FFD43B",
    size: "wide",
    topics: ["python", "trading", "low-latency"],
  },
  {
    repo: "Agentic-Rescue-Drone",
    title: "Agentic Rescue Drone",
    desc: "Autonomous drone project — perception, planning, and control loop integrated for high-stakes engineering. Real hardware, real flight.",
    tag: "robotics · ml",
    lang: "PY",
    langColor: "#FFD43B",
    size: "wide",
    topics: ["python", "ros", "cv"],
  },
  {
    repo: "AI-debate-researcher",
    title: "Debate Researcher",
    desc: "Multi-agent LLM system where agents argue and refine positions with live web research. Built to actually think, not vibe.",
    tag: "agentic ai",
    lang: "PY",
    langColor: "#FFD43B",
    size: "narrow",
    topics: ["python", "llm", "agents"],
  },
  {
    repo: "CodeColosseum",
    title: "CodeColosseum",
    desc: "LeetCode training tool that turns grind into a tournament. Gamified competitive practice for engineers.",
    tag: "product",
    lang: "TS",
    langColor: "#3178C6",
    size: "narrow",
    topics: ["typescript"],
  },
  {
    repo: "dateonlinkedin",
    title: "Date on LinkedIn",
    desc: "Dating platform exclusive to LinkedIn. Profile-first matching for people who care about what someone does.",
    tag: "consumer",
    lang: "TS",
    langColor: "#3178C6",
    size: "narrow",
    topics: ["typescript"],
  },
  {
    repo: "postal_code_visualizer",
    title: "Postal Code Visualizer",
    desc: "A small, honest project I built for my secondary school to visualize postal code regions. Good code scales with the people who use it.",
    tag: "web · civic",
    lang: "TS",
    langColor: "#3178C6",
    size: "full",
    topics: ["typescript", "data-viz"],
  },
];
