// Curated projects. Rendered as hard table rows in app.js.
// lang = short code (PY, TS, RS, GO, SOL, JS, C++) shown in the LANG column.
// langColor = solid color of the language swatch.
// liveDemo = optional URL to a deployed demo (rendered as DEMO column link).
// stars = number of github stars (shown on row hover for credibility).
window.PROJECTS = [
  {
    repo: "face-lock",
    title: "Face-Lock",
    desc: "Face-recognition CLI that auto-locks your laptop the moment you walk away. Computer vision + presence detection done right.",
    tag: "computer vision",
    lang: "PY",
    langColor: "#FFD43B",
    topics: ["python", "opencv", "cli"],
    liveDemo: "https://face-lock.site",
    stars: 320,
  },
  {
    repo: "face-lock-site",
    title: "Face-Lock.site",
    desc: "Marketing site for the Face-Lock CLI. Static + minimal, built to convert.",
    tag: "frontend",
    lang: "TS",
    langColor: "#3178C6",
    topics: ["typescript", "marketing"],
    liveDemo: "https://face-lock.site",
    stars: 4,
  },
  {
    repo: "shoppingshield",
    title: "ShoppingShield",
    desc: "Anti-scam platform that protects users from fraudulent e-commerce sites. Real-time risk scoring and browser tooling.",
    tag: "consumer · safety",
    lang: "TS",
    langColor: "#3178C6",
    topics: ["typescript", "security"],
    liveDemo: null,
    stars: 47,
  },
  {
    repo: "btc-perp-hft-framework",
    title: "BTC-Perp HFT",
    desc: "High-frequency trading framework for BTC perpetual futures on Coinbase International. Built for low-latency research and execution.",
    tag: "hft · infra",
    lang: "PY",
    langColor: "#FFD43B",
    topics: ["python", "trading", "low-latency"],
    liveDemo: null,
    stars: 89,
  },
  {
    repo: "Agentic-Rescue-Drone",
    title: "Agentic Rescue Drone",
    desc: "Autonomous drone project — perception, planning, and control loop integrated for high-stakes engineering. Real hardware, real flight.",
    tag: "robotics · ml",
    lang: "PY",
    langColor: "#FFD43B",
    topics: ["python", "ros", "cv"],
    liveDemo: null,
    stars: 156,
  },
  {
    repo: "AI-debate-researcher",
    title: "Debate Researcher",
    desc: "Multi-agent LLM system where agents argue and refine positions with live web research. Built to actually think, not vibe.",
    tag: "agentic ai",
    lang: "PY",
    langColor: "#FFD43B",
    topics: ["python", "llm", "agents"],
    liveDemo: null,
    stars: 41,
  },
  {
    repo: "CodeColosseum",
    title: "CodeColosseum",
    desc: "LeetCode training tool that turns grind into a tournament. Gamified competitive practice for engineers.",
    tag: "product",
    lang: "TS",
    langColor: "#3178C6",
    topics: ["typescript"],
    liveDemo: "https://codecolosseum.com",
    stars: 12,
  },
  {
    repo: "dateonlinkedin",
    title: "Date on LinkedIn",
    desc: "Dating platform exclusive to LinkedIn. Profile-first matching for people who care about what someone does.",
    tag: "consumer",
    lang: "TS",
    langColor: "#3178C6",
    topics: ["typescript"],
    liveDemo: null,
    stars: 8,
  },
  {
    repo: "postal_code_visualizer",
    title: "Postal Code Visualizer",
    desc: "A small, honest project I built for my secondary school to visualize postal code regions. Good code scales with the people who use it.",
    tag: "web · civic",
    lang: "TS",
    langColor: "#3178C6",
    topics: ["typescript", "data-viz"],
    liveDemo: "https://postal-code-visualizer.vercel.app",
    stars: 6,
  },
];
